/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package nidomiro.kdataloader

import kotlin.test.Test

class DataLoaderTest {
    @Test
    fun testSomeLibraryMethod() {

    }
}
