= Configuring KDataLoader

You have several options to customize KDataLoader to your needs.

IMPORTANT: After you created the KDataLoader you cannot change any set options.

== Custom cache

You can define a custom cache for the KDataLoader to use.
Through this method you can realize custom caching requirements like sharing the cache or distributing it.

The default cache instance can be instantiated with a custom (Mutable-)Map.
This map-instance will then be used by reference, therefore not copied.
When using this method keep in mind that you are not allowed to modify the map directly after setting it for the cache.

IMPORTANT: The cache needs to be "Coroutine"-Save ("Threadsave" for coroutines), because it can be called in parallel.

.Disabled cache
[source,kotlin]
----
dataLoader(batchLoader) {
    configure {
        cache {
            disabled
        }
    }
}
----

.Enabled cache (default)
[source,kotlin]
----
dataLoader(batchLoader) {
    configure {
        cache {
            enabled
        }
    }
}
----

.Custom cache
[source,kotlin]
----
dataLoader(batchLoader) {
    configure {
        cache {
            enabled with myCustomCacheInstance
        }
    }
}
----

.Custom cache
[source,kotlin]
----
dataLoader(batchLoader) {
    configure {
        cache {
            enabled()
        }
    }
}
----

== Caching Exceptions

Exceptional-states are cached by default.
An Exceptional state is when the `BatchLoader` returns `ExecutionResult.Failure()`.

.Default
[source,kotlin]
----
dataLoader(batchLoader) {
    configure {
        cacheExceptions = true
    }
}
----

== Batch load

Normally
