= What is KDataLoader

KDataLoader is a *pure* Kotlin implementation of https://github.com/graphql/dataloader[DataLoader].
It uses https://kotlinlang.org/docs/reference/coroutines-overview.html[Kotlin Coroutines] for parallel tasks.

== Motivation

The motivation behind a DataLoader is to save calls.
Let's say you use https://graphql.org/[GraphQL] and want to resolve a query.
This query can have a lot of duplicated data in its result.
The goal of a DataLoader is to reduce these duplicated calls and batch calls together.

== Example using GraphQL

If you have a query to fetch all projects with their members the result could look like this:

[source,json]
----
{
   "projects":[
      {
         "name":"Project A",
         "members":[
            {
               "id":1,
               "name":"John"
            },
            {
               "id":2,
               "name":"Anne"
            }
         ]
      },
      {
         "name":"Project B",
         "members":[
            {
               "id":2,
               "name":"Anne"
            }
         ]
      },
      {
         "name":"Project C",
         "members":[
            {
               "id":1,
               "name":"John"
            },
            {
               "id":3,
               "name":"Peter"
            }
         ]
      }
   ]
}
----

=== Naive approach

If you resolve this query naively you will have *6 requests*:

. fetch all Projects
. fetch John
. fetch Anne
. fetch Anne
. fetch John
. fetch Peter

=== DataLoader approach
Resolving the same query with a DataLoader takes *2 requests*:

. fetch all Projects
. fetch John, Anne and Peter in batch





