on:
  push:
    tags:
      - "v*"

jobs:
  test-and-build:
    name: Test and Build KDataLoader and publish lib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Test
        run: ./gradlew check${{matrix.postfix}}

      - name: Build
        run: ./gradlew assemble${{matrix.postfix}}

      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | gpg --import --batch
        env:
          GPG_SIGNING_KEY: ${{ secrets.SIGNING_SECRET_KEY }}

      - name: Publish to maven central
        run: >
          ./gradlew
          publish
        env:
          USE_GPG: 'true'
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

  test-and-build-macos:
    name: Publish macOS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | gpg --import --batch
        env:
          GPG_SIGNING_KEY: ${{ secrets.SIGNING_SECRET_KEY }}

      - name: Publish to maven central
        run: >
          ./gradlew
          publishApple
        env:
          USE_GPG: 'true'
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
