name: Build KDataLoader and publish lib

on:
    push:
        tags:
            - "v*"

jobs:
    test-and-build:
        name: Test and Build KDataLoader
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1
            -   name: Set up JDK 11
                uses: actions/setup-java@v1
                with:
                    java-version: 11
            -   name: Clean
                run: ./gradlew clean
            -   name: Test
                run: ./gradlew check
            -   name: Build
                run: ./gradlew assemble
            -   name: Publish to bintray
                run: ./gradlew -Pbintray_user=${{secrets.bintray_user}} -Pbintray_key=${{secrets.bintray_password}} publish
